project:
  type: website
  render:
    - "*.qmd"

website:
  title: Lattice
  favicon: assets/favicon.svg
  site-url: "https://lattice.yug.am"
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: Introduction
        href: index.qmd
      - text: Home
        href: index.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: css/styles.css
    toc: true
    page-layout: full
    

execute:
  freeze: auto


